# Generated by Django 3.1.7 on 2021-05-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventariosap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigosap', models.IntegerField(max_length=9)),
                ('descripcion', models.TextField(max_length=128)),
                ('ubicacion', models.TextField(max_length=11)),
                ('cantidad', models.IntegerField()),
                ('costounitario', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
