# Generated by Django 3.1.7 on 2021-05-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0002_auto_20210513_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosap',
            name='codigosap',
            field=models.IntegerField(unique=True),
        ),
    ]
