# Generated by Django 3.2.3 on 2021-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0003_auto_20210517_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosap',
            name='descripcion',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='inventariosap',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
